// This file was generated by github.com/vektah/gqlgen, DO NOT EDIT

package gqlschema

type Artist struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
type Song struct {
	ID       string  `json:"id"`
	Title    string  `json:"title"`
	Duration float64 `json:"duration"`
}
